Repository pytorch/torchtune, pull requests merged in 2024-11, with the labels that each got.

#1940 nit: Correct compile_loss return type hint
  torchtune/training/_compile.py
Labels: CLA Signed

#1941 Fix grad accum + FSDP CPU offload, pass None via CLI
  torchtune/config/_utils.py
  torchtune/training/_grad_scaler.py
Labels: CLA Signed

#1945 QAT tutorial nit
  docs/source/tutorials/qat_finetune.rst
Labels: CLA Signed

#1936 A more encompassing fix for offloading + ac
  tests/torchtune/training/test_activation_offloading.py
  torchtune/training/_activation_offloading.py
Labels: CLA Signed

#1949 Add Qwen2.5 to live docs
  docs/source/api_ref_models.rst
  torchtune/models/qwen2_5/_model_builders.py
Labels: CLA Signed

#1946 [Bug] model_type argument as str for checkpoints classes
  docs/source/deep_dives/checkpointer.rst
  torchtune/training/checkpointing/_checkpointer.py
Labels: CLA Signed

#1950 llama3.2 90b config updates + nits
  recipes/configs/llama3_2_vision/90B_full.yaml
  recipes/configs/llama3_2_vision/90B_lora.yaml
  recipes/configs/llama3_2_vision/90B_qlora.yaml
  recipes/full_finetune_distributed.py
  recipes/full_finetune_single_device.py
  recipes/lora_finetune_distributed.py
  recipes/lora_finetune_single_device.py
  torchtune/utils/__init__.py
Labels: CLA Signed

#1826 Add Ascend NPU as a backend
  recipes/full_finetune_single_device.py
  recipes/lora_finetune_single_device.py
  tests/torchtune/utils/test_device.py
  torchtune/training/memory.py
  torchtune/training/precision.py
  torchtune/utils/__init__.py
  torchtune/utils/_device.py
Labels: CLA Signed

#1952 fix missing key
  torchtune/training/checkpointing/_checkpointer.py
Labels: CLA Signed

#1948 update memory optimization tutorial
  docs/source/tutorials/memory_optimizations.rst
Labels: CLA Signed

#1963 add expandable segment to integration tests
  .github/workflows/regression_test.yaml
Labels: CLA Signed

#1967 Fix check in `load_from_full_state_dict` for modified state dicts
  torchtune/training/_distributed.py
Labels: CLA Signed, fb-exported

#1970 Update torchtune generation to be more flexible
  torchtune/generation/_generation.py
Labels: CLA Signed, fb-exported

#1972 typo
  docs/source/tutorials/memory_optimizations.rst
Labels: CLA Signed

#1854 Update QAT: add grad clipping, torch.compile, collate fn
  recipes/configs/llama2/7B_qat_full.yaml
  recipes/configs/llama3/8B_qat_full.yaml
  recipes/qat_distributed.py
Labels: CLA Signed

#1974 VQA Documentation
  docs/source/api_ref_datasets.rst
Labels: CLA Signed

#1976 Convert all non-rgb images to rgb
  torchtune/models/clip/_transform.py
Labels: CLA Signed

#1904 Early fusion multimodal models
  tests/torchtune/modules/model_fusion/test_deep_fusion.py
  tests/torchtune/modules/model_fusion/test_early_fusion.py
  tests/torchtune/modules/model_fusion/test_fusion_embed.py
  tests/torchtune/modules/model_fusion/test_fusion_layers.py
  torchtune/modules/model_fusion/__init__.py
  torchtune/modules/model_fusion/_deep_fusion.py
  torchtune/modules/model_fusion/_early_fusion.py
  torchtune/modules/model_fusion/_fusion_layers.py
  torchtune/modules/model_fusion/_fusion_utils.py
  torchtune/modules/peft/_utils.py
Labels: CLA Signed, rfc

#1964 Refactor Recipe State Dict Code
  docs/source/api_ref_modules.rst
  docs/source/api_ref_training.rst
  recipes/full_finetune_distributed.py
  recipes/knowledge_distillation_distributed.py
  recipes/knowledge_distillation_single_device.py
  recipes/lora_dpo_distributed.py
  recipes/lora_dpo_single_device.py
  recipes/lora_finetune_distributed.py
  recipes/lora_finetune_single_device.py
  recipes/qat_distributed.py
  tests/recipes/test_full_finetune_distributed.py
  tests/recipes/test_full_finetune_single_device.py
  tests/torchtune/modules/peft/test_utils.py
  tests/torchtune/training/test_distributed.py
  torchtune/modules/peft/__init__.py
  torchtune/modules/peft/_utils.py
  torchtune/training/__init__.py
  torchtune/training/_distributed.py
Labels: CLA Signed

#1961 Update KV Cache to use num_kv_heads instead of num_heads
  tests/torchtune/models/llama2/scripts/compare_fused_attention.py
  tests/torchtune/models/llama2/scripts/compare_lora_attention.py
  tests/torchtune/modules/test_attention.py
  torchtune/models/gemma2/_attention.py
  torchtune/modules/attention.py
  torchtune/modules/kv_cache.py
Labels: CLA Signed

#1981 Migrate to ``epochs: 1`` in all configs
  recipes/configs/dev/8B_full_experimental.yaml
  recipes/configs/gemma/2B_full.yaml
  recipes/configs/gemma/2B_lora.yaml
  recipes/configs/gemma/2B_lora_single_device.yaml
  recipes/configs/gemma/2B_qlora_single_device.yaml
  recipes/configs/gemma/7B_lora.yaml
  recipes/configs/gemma/7B_qlora_single_device.yaml
  recipes/configs/gemma2/27B_lora.yaml
  recipes/configs/gemma2/27B_qlora_single_device.yaml
  recipes/configs/gemma2/2B_full.yaml
  recipes/configs/gemma2/2B_lora.yaml
  recipes/configs/gemma2/2B_lora_single_device.yaml
  recipes/configs/gemma2/2B_qlora_single_device.yaml
  recipes/configs/gemma2/9B_lora.yaml
  recipes/configs/gemma2/9B_qlora_single_device.yaml
  recipes/configs/llama2/13B_full.yaml
  recipes/configs/llama2/7B_full.yaml
  recipes/configs/llama2/7B_full_low_memory.yaml
  recipes/configs/llama2/7B_qat_full.yaml
  recipes/configs/llama3/70B_full.yaml
  recipes/configs/llama3/8B_full.yaml
  recipes/configs/llama3/8B_full_single_device.yaml
  recipes/configs/llama3/8B_qat_full.yaml
  recipes/configs/llama3_1/70B_full.yaml
  recipes/configs/llama3_1/8B_full.yaml
  recipes/configs/llama3_1/8B_full_single_device.yaml
  recipes/configs/llama3_2/1B_full.yaml
  recipes/configs/llama3_2/1B_full_single_device.yaml
  recipes/configs/llama3_2/3B_full.yaml
  recipes/configs/llama3_2/3B_full_single_device.yaml
  recipes/configs/mistral/7B_full.yaml
  recipes/configs/mistral/7B_full_low_memory.yaml
  recipes/configs/mistral/7B_lora.yaml
  recipes/configs/mistral/7B_lora_single_device.yaml
  recipes/configs/mistral/7B_qlora_single_device.yaml
  recipes/configs/qwen2/1.5B_full.yaml
  recipes/configs/qwen2_5/1_5B_full.yaml
Labels: CLA Signed

#1987 Add **quantization_kwargs to ``FrozenNF4Linear`` and ``LoRALinear`` and ``DoRALinear``
  tests/torchtune/modules/low_precision/test_nf4_linear.py
  tests/torchtune/modules/peft/test_dora.py
  tests/torchtune/modules/peft/test_lora.py
  torchtune/modules/low_precision/nf4_linear.py
  torchtune/modules/peft/dora.py
  torchtune/modules/peft/lora.py
Labels: CLA Signed

#1988 Enables Python 3.13 for nightly builds
  .github/workflows/build_linux_wheels.yaml
Labels: CLA Signed

#1989 Adding MM eval tests / attention bugfixes
  tests/cache_artifacts.sh
  tests/recipes/test_eleuther_eval.py
  tests/recipes/utils.py
  tests/test_utils.py
  tests/torchtune/modules/test_transformer_decoder.py
  torchtune/models/gemma2/_attention.py
  torchtune/modules/attention.py
  torchtune/modules/transformer.py
Labels: CLA Signed

#1982 nit: Fix/add some type annotations
  docs/source/deep_dives/configs.rst
  torchtune/config/_instantiate.py
  torchtune/config/_parse.py
  torchtune/modules/common_utils.py
Labels: CLA Signed

#2000 Fixing `special_tokens` arg in `Llama3VisionTransform`
  torchtune/models/llama3_2_vision/_model_builders.py
  torchtune/models/llama3_2_vision/_transform.py
Labels: CLA Signed

#1979 Recent updates to the README
  README.md
Labels: CLA Signed

#2009 Bump version to 0.5.0
  version.txt
Labels: CLA Signed

#2011 Create _export directory in torchtune
  torchtune/modules/_export/README.md
Labels: CLA Signed, fb-exported

#2015 torchrun defaults for concurrent distributed training jobs
  torchtune/_cli/run.py
Labels: CLA Signed

#2016 Remove unused FSDP components
  docs/source/api_ref_modules.rst
  docs/source/api_ref_training.rst
  docs/source/tutorials/lora_finetune.rst
  docs/source/tutorials/qat_finetune.rst
  recipes/lora_dpo_single_device.py
  tests/torchtune/modules/peft/test_utils.py
  tests/torchtune/training/test_distributed.py
  torchtune/modules/peft/__init__.py
  torchtune/modules/peft/_utils.py
  torchtune/modules/peft/lora.py
  torchtune/training/__init__.py
  torchtune/training/_distributed.py
Labels: CLA Signed

#1973 2D RoPE + CLIP updates
  tests/torchtune/models/phi3/test_phi3_position_embeddings.py
  tests/torchtune/modules/test_position_embeddings.py
  tests/torchtune/modules/test_vision_transformer.py
  tests/torchtune/training/test_distributed.py
  torchtune/models/clip/_component_builders.py
  torchtune/models/llama3/_component_builders.py
  torchtune/models/llama3/_model_builders.py
  torchtune/models/llama3_2_vision/_model_builders.py
  torchtune/modules/__init__.py
  torchtune/modules/position_embeddings.py
  torchtune/modules/vision_transformer.py
Labels: CLA Signed

#2020 Some KD recipe cleanup
  recipes/knowledge_distillation_distributed.py
  recipes/knowledge_distillation_single_device.py
  torchtune/training/_compile.py
  torchtune/training/memory.py
Labels: CLA Signed

#1991 Remove lr_scheduler requirement in lora_dpo_single_device
  recipes/lora_dpo_single_device.py
Labels: CLA Signed

#1877 chore: remove PyTorch 2.5.0 checks
  docs/source/tutorials/memory_optimizations.rst
  recipes/lora_finetune_distributed.py
  tests/torchtune/modules/test_attention_utils.py
  torchtune/modules/attention_utils.py
  torchtune/modules/common_utils.py
  torchtune/training/_activation_offloading.py
  torchtune/training/_compile.py
  torchtune/utils/_import_guard.py
Labels: CLA Signed

#1868 Make tokenize tests readable
  tests/torchtune/models/gemma/test_gemma_tokenizer.py
  tests/torchtune/models/llama2/test_llama2_tokenizer.py
  tests/torchtune/models/llama3/test_llama3_tokenizer.py
  tests/torchtune/models/mistral/test_mistral_tokenizer.py
  tests/torchtune/models/phi3/test_phi3_tokenizer.py
  tests/torchtune/models/qwen2/test_qwen2_tokenizer.py
Labels: CLA Signed

#2003 add flags to readme
  README.md
Labels: CLA Signed

#2022 [WIP] Reducing eval vision tests runtime
  tests/recipes/test_eleuther_eval.py
Labels: CLA Signed

#2030 log rank zero everywhere
  recipes/full_finetune_distributed.py
  recipes/knowledge_distillation_distributed.py
  recipes/lora_dpo_distributed.py
  recipes/lora_finetune_distributed.py
  recipes/qat_distributed.py
  torchtune/utils/_logging.py
Labels: CLA Signed

#2017 Add LR Scheduler to full finetune distributed
  recipes/full_finetune_distributed.py
Labels: CLA Signed

#2028 Fix Qlora/lora for 3.2 vision
  recipes/configs/llama3_2_vision/11B_qlora.yaml
  recipes/configs/llama3_2_vision/11B_qlora_single_device.yaml
  recipes/configs/llama3_2_vision/90B_full.yaml
  recipes/configs/llama3_2_vision/90B_lora.yaml
  recipes/configs/llama3_2_vision/90B_qlora.yaml
  torchtune/models/llama3_2_vision/_component_builders.py
  torchtune/modules/peft/dora.py
  torchtune/modules/peft/lora.py
Labels: CLA Signed

#1969 CLIP Text Encoder
  tests/torchtune/models/clip/test_clip_text_encoder.py
  tests/torchtune/models/clip/test_clip_tokenizer.py
  torchtune/models/clip/__init__.py
  torchtune/models/clip/_component_builders.py
  torchtune/models/clip/_convert_weights.py
  torchtune/models/clip/_model_builders.py
  torchtune/models/clip/_text_encoder.py
  torchtune/models/clip/_tokenizer.py
  torchtune/training/checkpointing/_checkpointer.py
  torchtune/training/checkpointing/_utils.py
Labels: CLA Signed

#2002 feat(cli): allow users to download models from Kaggle
  docs/source/tune_cli.rst
  pyproject.toml
  tests/torchtune/_cli/test_download.py
  torchtune/_cli/download.py
Labels: CLA Signed

#2047 Remove deprecated `TiedEmbeddingTransformerDecoder`
  torchtune/modules/__init__.py
  torchtune/modules/transformer.py
Labels: CLA Signed

#2046 Use hf transfer as default
  pyproject.toml
  torchtune/__init__.py
Labels: CLA Signed

#2043 Fix issue in loading mixed precision vocab pruned models during torchtune generation for evaluation
  tests/torchtune/training/test_precision.py
  torchtune/training/precision.py
Labels: CLA Signed, fb-exported

#2054 Switch to PyTorch's built-in RMSNorm
  tests/torchtune/modules/test_rms_norm.py
  torchtune/modules/rms_norm.py
Labels: CLA Signed

#2068 [export] Add exportable position embedding
  tests/torchtune/modules/_export/test_export_position_embeddings.py
  torchtune/modules/_export/_position_embeddings.py
Labels: CLA Signed

#1931 Add support for QAT + LoRA
  README.md
  recipes/configs/llama3/8B_qat_lora.yaml
  recipes/configs/llama3_1/8B_qat_lora.yaml
  recipes/configs/llama3_2/1B_qat_lora.yaml
  recipes/configs/llama3_2/3B_qat_lora.yaml
  recipes/qat_lora_finetune_distributed.py
  tests/recipes/test_qat_lora_finetune_distributed.py
  tests/torchtune/modules/peft/test_lora.py
  torchtune/_recipe_registry.py
  torchtune/modules/peft/__init__.py
  torchtune/modules/peft/lora.py
  torchtune/training/quantization.py
Labels: CLA Signed

#2072 Add ability to shard custom layers for DPO and LoRA distributed
  recipes/configs/llama3/70B_lora.yaml
  recipes/configs/llama3_1/70B_lora.yaml
  recipes/configs/qwen2_5/32B_lora.yaml
  recipes/configs/qwen2_5/72B_lora.yaml
  recipes/lora_dpo_distributed.py
  recipes/lora_finetune_distributed.py
Labels: CLA Signed

#2075 [ez] remove stale pytorch version check
  recipes/full_finetune_distributed.py
  recipes/qat_distributed.py
Labels: CLA Signed

#2080 Fail early with `packed=True` on MM datasets.
  tests/torchtune/datasets/multimodal/test_llava_instruct_dataset.py
  tests/torchtune/datasets/multimodal/test_multimodal_chat_dataset.py
  tests/torchtune/datasets/multimodal/test_the_cauldron_dataset.py
  tests/torchtune/datasets/multimodal/test_vqa_dataset.py
  torchtune/datasets/multimodal/_llava_instruct.py
  torchtune/datasets/multimodal/_multimodal.py
  torchtune/datasets/multimodal/_the_cauldron.py
  torchtune/datasets/multimodal/_vqa.py
Labels: CLA Signed

#2079 Error message on ``packed=True`` for stack exchange dataset
  tests/torchtune/datasets/test_hh_rlhf_helpful_dataset.py
  tests/torchtune/datasets/test_preference_dataset.py
  tests/torchtune/datasets/test_stack_exchange_paired_dataset.py
  torchtune/datasets/_preference.py
Labels: CLA Signed

#2063 Deprecate `SimpoLoss`
  recipes/lora_dpo_distributed.py
  recipes/lora_dpo_single_device.py
  torchtune/rlhf/loss/dpo.py
Labels: CLA Signed

#2091 DPO Recipe Doc
  docs/source/index.rst
  docs/source/recipes/dpo.rst
  docs/source/recipes/lora_finetune_single_device.rst
  docs/source/recipes/recipes_overview.rst
Labels: CLA Signed
