Repository pytorch/torchtune, pull requests merged in 2024-07, with the labels that each got.

#1132 update ao to latest patch
  pyproject.toml
Labels: CLA Signed

#1135 Fix RegEx to parse out acc numbers for eval recipe test
  tests/recipes/test_eleuther_eval.py
Labels: CLA Signed

#1137 Remove warning from Phi-3 tokenizer
  torchtune/models/phi3/_model_builders.py
Labels: documentation, CLA Signed

#1082 Tokenizer redesign for better model-specific feature support
  docs/source/api_ref_config.rst
  docs/source/api_ref_models.rst
  docs/source/api_ref_modules.rst
  docs/source/deep_dives/configs.rst
  docs/source/tutorials/chat.rst
  docs/source/tutorials/datasets.rst
  recipes/eleuther_eval.py
  tests/test_utils.py
  tests/torchtune/datasets/test_alpaca_dataset.py
  tests/torchtune/datasets/test_cnn_dailymail_dataset.py
  tests/torchtune/datasets/test_grammar_dataset.py
  tests/torchtune/datasets/test_samsum_dataset.py
  tests/torchtune/datasets/test_slimorca_dataset.py
  tests/torchtune/datasets/test_wikitext_dataset.py
  tests/torchtune/models/gemma/test_gemma_tokenizer.py
  tests/torchtune/models/llama2/test_llama2_tokenizer.py
  tests/torchtune/models/llama2/test_lora_llama2.py
  tests/torchtune/models/llama3/test_llama3.py
  tests/torchtune/models/llama3/test_llama3_tokenizer.py
  tests/torchtune/models/mistral/test_mistral.py
  tests/torchtune/models/mistral/test_mistral_classifier.py
  tests/torchtune/models/mistral/test_mistral_tokenizer.py
  tests/torchtune/models/phi3/test_phi3_tokenizer.py
  tests/torchtune/modules/tokenizers/test_sentencepiece.py
  tests/torchtune/modules/tokenizers/test_tiktoken.py
  tests/torchtune/modules/tokenizers/test_utils.py
  torchtune/datasets/_alpaca.py
  torchtune/datasets/_chat.py
  torchtune/datasets/_cnn_dailymail.py
  torchtune/datasets/_grammar.py
  torchtune/datasets/_instruct.py
  torchtune/datasets/_preference.py
  torchtune/datasets/_samsum.py
  torchtune/datasets/_slimorca.py
  torchtune/datasets/_stack_exchanged_paired.py
  torchtune/datasets/_text_completion.py
  torchtune/datasets/_wikitext.py
  torchtune/models/gemma/__init__.py
  torchtune/models/gemma/_model_builders.py
  torchtune/models/gemma/_tokenizer.py
  torchtune/models/llama2/__init__.py
  torchtune/models/llama2/_model_builders.py
  torchtune/models/llama2/_tokenizer.py
  torchtune/models/llama3/__init__.py
  torchtune/models/llama3/_model_builders.py
  torchtune/models/llama3/_tokenizer.py
  torchtune/models/mistral/__init__.py
  torchtune/models/mistral/_model_builders.py
  torchtune/models/mistral/_tokenizer.py
  torchtune/models/phi3/__init__.py
  torchtune/models/phi3/_model_builders.py
  torchtune/models/phi3/_tokenizer.py
  torchtune/modules/tokenizers/__init__.py
  torchtune/modules/tokenizers/_sentencepiece.py
  torchtune/modules/tokenizers/_tiktoken.py
  torchtune/modules/tokenizers/_utils.py
Labels: CLA Signed

#1138 Interleaved image support in tokenizers
  docs/source/api_ref_data.rst
  tests/test_utils.py
  tests/torchtune/data/test_chat_formats.py
  tests/torchtune/data/test_converters.py
  tests/torchtune/datasets/test_chat_dataset.py
  tests/torchtune/models/llama3/test_llama3_tokenizer.py
  torchtune/data/__init__.py
  torchtune/data/_chat_formats.py
  torchtune/data/_converters.py
  torchtune/data/_types.py
  torchtune/models/llama3/_tokenizer.py
  torchtune/models/phi3/_tokenizer.py
  torchtune/modules/tokenizers/_utils.py
Labels: CLA Signed

#1084 [CLIP][IMAGE TRANSFORMS] Image transforms for clip encoder
  docs/source/api_ref_modules.rst
  pyproject.toml
  tests/torchtune/models/clip/__init__.py
  tests/torchtune/models/clip/test_clip_image_transform.py
  tests/torchtune/modules/transforms/test_get_canvas_best_fit.py
  tests/torchtune/modules/transforms/test_resize_with_pad.py
  tests/torchtune/modules/transforms/test_tile_crop.py
  torchtune/models/clip/__init__.py
  torchtune/models/clip/_model_builders.py
  torchtune/models/clip/_transforms.py
  torchtune/modules/transforms/__init__.py
  torchtune/modules/transforms/vision_utils/__init__.py
  torchtune/modules/transforms/vision_utils/get_canvas_best_fit.py
  torchtune/modules/transforms/vision_utils/resize_with_pad.py
  torchtune/modules/transforms/vision_utils/tile_crop.py
Labels: CLA Signed

#1147 Making `add_eos` optional in text completion dataset
  docs/source/tutorials/datasets.rst
  tests/torchtune/datasets/test_text_completion_dataset.py
  torchtune/datasets/_text_completion.py
Labels: CLA Signed

#1127 [CLIP ENCODER] Vision Transform for Clip encoder
  docs/source/api_ref_models.rst
  docs/source/api_ref_modules.rst
  tests/torchtune/models/clip/test_positional_embeddings.py
  tests/torchtune/modules/test_layernorm.py
  tests/torchtune/modules/test_transformer_decoder.py
  tests/torchtune/modules/test_vision_transformer.py
  torchtune/models/clip/__init__.py
  torchtune/models/clip/_component_builders.py
  torchtune/models/clip/_position_embeddings.py
  torchtune/models/clip/_transforms.py
  torchtune/modules/__init__.py
  torchtune/modules/layer_norm.py
  torchtune/modules/vision_transformer.py
Labels: CLA Signed

#1151 Miscellaneous CI, dependency, and version fixes
  .github/workflows/build_docs.yaml
  .github/workflows/gpu_test.yaml
  .github/workflows/recipe_test.yaml
  .github/workflows/recipe_test_nightly.yaml
  .github/workflows/regression_test.yaml
  .github/workflows/unit_test.yaml
  README.md
  pyproject.toml
  tests/torchtune/utils/test_distributed.py
  torchtune/modules/low_precision/_register_nf4_dispatch_ops.py
  torchtune/modules/low_precision/_utils.py
  torchtune/utils/quantization.py
Labels: CLA Signed

#1141 Vision cross attention mask transform
  docs/source/api_ref_modules.rst
  tests/torchtune/modules/transforms/test_transforms.py
  torchtune/modules/transforms/__init__.py
  torchtune/modules/transforms/_transforms.py
Labels: CLA Signed

#1161 Update code-llama download path and resume_from_checkpoint
  README.md
  recipes/configs/code_llama2/7B_full_low_memory.yaml
  recipes/configs/code_llama2/7B_lora_single_device.yaml
  recipes/configs/code_llama2/7B_qlora_single_device.yaml
Labels: CLA Signed

#1162 Add version check for FSDP2 recipe
  recipes/dev/lora_finetune_fsdp2.py
Labels: CLA Signed

#1164 Updated Project.toml to include dev Configs
  pyproject.toml
Labels: CLA Signed

#1168 Reverting Gemma checkpointing logic
  tests/torchtune/utils/test_checkpointer.py
  torchtune/models/gemma/__init__.py
  torchtune/models/gemma/_convert_weights.py
  torchtune/utils/_checkpointing/_checkpointer.py
Labels: CLA Signed

#1167 update models docs
  docs/source/api_ref_models.rst
  torchtune/models/clip/__init__.py
  torchtune/models/clip/_component_builders.py
  torchtune/models/clip/_model_builders.py
  torchtune/models/clip/_position_embeddings.py
  torchtune/models/code_llama2/_model_builders.py
  torchtune/models/gemma/_tokenizer.py
  torchtune/models/llama2/__init__.py
  torchtune/models/llama2/_model_builders.py
  torchtune/models/llama2/_tokenizer.py
  torchtune/models/llama3/__init__.py
  torchtune/models/mistral/_model_builders.py
  torchtune/models/mistral/_tokenizer.py
  torchtune/models/phi3/_tokenizer.py
Labels: CLA Signed

#1169 Fix Gemma 7B checkpoint save
  torchtune/models/convert_weights.py
  torchtune/utils/_checkpointing/_checkpointer.py
Labels: CLA Signed

#1170 Update utils docs
  docs/source/api_ref_models.rst
  torchtune/models/gemma/__init__.py
  torchtune/models/mistral/_component_builders.py
  torchtune/utils/_checkpointing/_checkpointer.py
  torchtune/utils/_profiler.py
  torchtune/utils/collate.py
  torchtune/utils/quantization.py
Labels: CLA Signed

#1171 Update dataset docstrings
  torchtune/datasets/_alpaca.py
  torchtune/datasets/_chat.py
  torchtune/datasets/_concat.py
  torchtune/datasets/_grammar.py
  torchtune/datasets/_instruct.py
  torchtune/datasets/_preference.py
  torchtune/datasets/_samsum.py
  torchtune/datasets/_slimorca.py
  torchtune/datasets/_text_completion.py
Labels: CLA Signed

#1173 Updated module links
  torchtune/modules/attention.py
  torchtune/modules/position_embeddings.py
  torchtune/modules/rms_norm.py
Labels: CLA Signed

#1172 Updated dev install instructions
  CONTRIBUTING.md
Labels: CLA Signed

#1174 Fix llama3 chat tutorial
  docs/source/tutorials/chat.rst
Labels: CLA Signed

#1176 Fix incorrect date check for ao nightlies
  torchtune/modules/low_precision/_utils.py
  torchtune/utils/quantization.py
Labels: CLA Signed

#1180 Update CLI docs
  docs/source/tune_cli.rst
Labels: CLA Signed

#1181 Update docs for ConcatDataset
  docs/source/tutorials/datasets.rst
  torchtune/datasets/_concat.py
Labels: CLA Signed

#1182 [EZ] Fix comment formatting in code-llama configs
  recipes/configs/code_llama2/7B_full_low_memory.yaml
  recipes/configs/code_llama2/7B_lora_single_device.yaml
  recipes/configs/code_llama2/7B_qlora_single_device.yaml
Labels: CLA Signed

#1184 fix torchtune internal CI after the `quantize_` API refactor
  torchtune/utils/quantization.py
Labels: CLA Signed, fb-exported

#1190 Updated Gemma configs and Documentation
  docs/source/api_ref_models.rst
  recipes/configs/gemma/2B_full.yaml
  recipes/configs/gemma/2B_lora.yaml
  recipes/configs/gemma/2B_lora_single_device.yaml
  recipes/configs/gemma/2B_qlora_single_device.yaml
  recipes/configs/gemma/7B_full.yaml
  recipes/configs/gemma/7B_lora.yaml
  recipes/configs/gemma/7B_lora_single_device.yaml
  recipes/configs/gemma/7B_qlora_single_device.yaml
Labels: CLA Signed

#1192 Point layer norm to torch documentation
  torchtune/modules/layer_norm.py
Labels: CLA Signed

#1195 Test codev flow
  torchtune/utils/quantization.py
Labels: CLA Signed, fb-exported

#1105 [doc] Add QAT tutorial
  docs/source/_static/img/qat_diagram.png
  docs/source/index.rst
  docs/source/tutorials/qat_finetune.rst
Labels: CLA Signed

#1197 DPO Loss refactor
  docs/source/api_ref_modules.rst
  recipes/configs/llama2/7B_lora_dpo.yaml
  recipes/configs/llama2/7B_lora_dpo_single_device.yaml
  recipes/lora_dpo_distributed.py
  recipes/lora_dpo_single_device.py
  tests/torchtune/modules/loss/test_dpo_loss.py
  torchtune/modules/loss/__init__.py
  torchtune/modules/loss/dpo.py
Labels: CLA Signed

#1203 Expose `split` in dataset builders
  torchtune/datasets/_alpaca.py
  torchtune/datasets/_chat.py
  torchtune/datasets/_cnn_dailymail.py
  torchtune/datasets/_grammar.py
  torchtune/datasets/_samsum.py
  torchtune/datasets/_slimorca.py
  torchtune/datasets/_stack_exchanged_paired.py
  torchtune/datasets/_wikitext.py
Labels: CLA Signed

#1204 Fix check for valid config for 70B training with fused optimizer
  recipes/full_finetune_distributed.py
Labels: CLA Signed

#973 Add support for non-incremental decoding + unit test
  tests/torchtune/utils/test_generation.py
  torchtune/modules/transformer.py
  torchtune/utils/_generation.py
Labels: CLA Signed

#1205 [DO NOT MERGE YET] Bump version number to 0.2.1
  version.txt
Labels: CLA Signed

#1207 Make kv_cache Optional
  recipes/configs/generation.yaml
  recipes/generate.py
Labels: CLA Signed

#1208 Llama 3.1 Configs and Code
  README.md
  docs/source/api_ref_models.rst
  recipes/configs/generation.yaml
  recipes/configs/llama3_1/70B_full.yaml
  recipes/configs/llama3_1/70B_lora.yaml
  recipes/configs/llama3_1/8B_full.yaml
  recipes/configs/llama3_1/8B_full_single_device.yaml
  recipes/configs/llama3_1/8B_lora.yaml
  recipes/configs/llama3_1/8B_lora_single_device.yaml
  recipes/configs/llama3_1/8B_qlora_single_device.yaml
  torchtune/_recipe_registry.py
  torchtune/models/llama3_1/__init__.py
  torchtune/models/llama3_1/_component_builders.py
  torchtune/models/llama3_1/_model_builders.py
  torchtune/models/llama3_1/_position_embeddings.py
Labels: CLA Signed

#1210 Checkpointer Save "adapter_only" Option
  tests/torchtune/utils/test_checkpointer.py
  torchtune/utils/_checkpointing/_checkpointer.py
Labels: CLA Signed

#1160 Generalizing reward models
  docs/source/api_ref_models.rst
  tests/torchtune/utils/test_checkpointer.py
  torchtune/models/llama2/__init__.py
  torchtune/models/llama2/_component_builders.py
  torchtune/models/llama2/_model_builders.py
  torchtune/models/mistral/__init__.py
  torchtune/models/mistral/_component_builders.py
  torchtune/models/mistral/_model_builders.py
  torchtune/modules/rlhf/__init__.py
  torchtune/modules/rlhf/utils/__init__.py
  torchtune/modules/rlhf/utils/_convert_weights.py
  torchtune/utils/_checkpointing/_checkpointer.py
  torchtune/utils/_checkpointing/_checkpointer_utils.py
Labels: CLA Signed

#1217 Add back 'NOTE' fixture to README
  README.md
Labels: CLA Signed

#1216 Add test for Llama3.1 ScaledRoPE
  tests/torchtune/models/llama3_1/test_position_embeddings.py
  torchtune/models/llama3_1/_component_builders.py
  torchtune/models/llama3_1/_position_embeddings.py
Labels: CLA Signed

#1218 Allow BF16 dtype support on CPU
  docs/source/deep_dives/recipe_deepdive.rst
  recipes/eleuther_eval.py
  recipes/generate.py
  recipes/quantize.py
  torchtune/utils/precision.py
Labels: CLA Signed

#1134 Issue #1123 datasets doc improvement
  docs/source/tutorials/datasets.rst
  torchtune/datasets/_chat.py
  torchtune/datasets/_instruct.py
  torchtune/datasets/_preference.py
  torchtune/datasets/_text_completion.py
Labels: CLA Signed

#1227 Unify configs for Phi3
  recipes/configs/phi3/mini_full.yaml
  recipes/configs/phi3/mini_full_low_memory.yaml
  recipes/configs/phi3/mini_lora.yaml
  recipes/configs/phi3/mini_lora_single_device.yaml
  recipes/configs/phi3/mini_qlora_single_device.yaml
Labels: CLA Signed

#1235 [memory Improvement] delete logits before bwd
  recipes/full_finetune_distributed.py
  recipes/full_finetune_single_device.py
  recipes/lora_finetune_single_device.py
  recipes/qat_distributed.py
Labels: CLA Signed

#1238 Remove unused variables
  torchtune/modules/transformer.py
Labels: CLA Signed

#1219 Remove most of the PTQ receipe
  docs/source/tutorials/e2e_flow.rst
  docs/source/tutorials/llama3.rst
  recipes/configs/quantization.yaml
  recipes/quantization.md
  recipes/quantize.py
  torchtune/utils/quantization.py
Labels: CLA Signed

#1240 Fixing pydoclint
  .pre-commit-config.yaml
  pyproject.toml
  recipes/dev/lora_finetune_fsdp2.py
  recipes/eleuther_eval.py
  recipes/full_finetune_distributed.py
  recipes/full_finetune_single_device.py
  recipes/lora_dpo_distributed.py
  recipes/lora_dpo_single_device.py
  recipes/lora_finetune_distributed.py
  recipes/lora_finetune_single_device.py
  recipes/qat_distributed.py
  tests/test_profiler.py
  torchtune/config/_utils.py
  torchtune/data/_types.py
  torchtune/datasets/_chat.py
  torchtune/datasets/_concat.py
  torchtune/datasets/_instruct.py
  torchtune/models/clip/_position_embeddings.py
  torchtune/models/clip/_transforms.py
  torchtune/models/convert_weights.py
  torchtune/models/llama3/_tokenizer.py
  torchtune/models/mistral/_tokenizer.py
  torchtune/modules/kv_cache.py
  torchtune/modules/layer_norm.py
  torchtune/modules/tokenizers/_tiktoken.py
  torchtune/modules/tokenizers/_utils.py
  torchtune/modules/transforms/_transforms.py
  torchtune/modules/transforms/vision_utils/resize_with_pad.py
  torchtune/modules/vision_transformer.py
  torchtune/utils/_checkpointing/_checkpointer.py
  torchtune/utils/_checkpointing/_checkpointer_utils.py
  torchtune/utils/_distributed.py
  torchtune/utils/_profiler.py
  torchtune/utils/collate.py
  torchtune/utils/precision.py
Labels: CLA Signed

#1220 Added adapter_only option to LoRA
  docs/source/deep_dives/checkpointer.rst
  recipes/configs/code_llama2/7B_lora_single_device.yaml
  recipes/configs/code_llama2/7B_qlora_single_device.yaml
  recipes/configs/dev/llama2/13B_lora_fsdp2.yaml
  recipes/configs/dev/llama2/70B_lora_fsdp2.yaml
  recipes/configs/dev/llama2/70B_qlora_fsdp2.yaml
  recipes/configs/dev/llama2/7B_lora_fsdp2.yaml
  recipes/configs/dev/llama2/7B_qlora_fsdp2.yaml
  recipes/configs/gemma/2B_lora.yaml
  recipes/configs/gemma/2B_lora_single_device.yaml
  recipes/configs/gemma/2B_qlora_single_device.yaml
  recipes/configs/gemma/7B_lora.yaml
  recipes/configs/gemma/7B_lora_single_device.yaml
  recipes/configs/gemma/7B_qlora_single_device.yaml
  recipes/configs/llama2/13B_lora.yaml
  recipes/configs/llama2/13B_qlora_single_device.yaml
  recipes/configs/llama2/70B_lora.yaml
  recipes/configs/llama2/7B_lora.yaml
  recipes/configs/llama2/7B_lora_dpo.yaml
  recipes/configs/llama2/7B_lora_dpo_single_device.yaml
  recipes/configs/llama2/7B_lora_single_device.yaml
  recipes/configs/llama2/7B_qlora_single_device.yaml
  recipes/configs/llama3/70B_lora.yaml
  recipes/configs/llama3/8B_lora.yaml
  recipes/configs/llama3/8B_lora_single_device.yaml
  recipes/configs/llama3/8B_qlora_single_device.yaml
  recipes/configs/llama3_1/70B_lora.yaml
  recipes/configs/llama3_1/8B_lora.yaml
  recipes/configs/llama3_1/8B_lora_single_device.yaml
  recipes/configs/llama3_1/8B_qlora_single_device.yaml
  recipes/configs/mistral/7B_lora.yaml
  recipes/configs/mistral/7B_lora_single_device.yaml
  recipes/configs/mistral/7B_qlora_single_device.yaml
  recipes/configs/phi3/mini_lora.yaml
  recipes/configs/phi3/mini_lora_single_device.yaml
  recipes/configs/phi3/mini_qlora_single_device.yaml
  recipes/lora_dpo_distributed.py
  recipes/lora_dpo_single_device.py
  recipes/lora_finetune_distributed.py
  recipes/lora_finetune_single_device.py
  torchtune/utils/_checkpointing/_checkpointer.py
Labels: CLA Signed

#1119 NF4 quantization of linear layers without LoRA applied
  tests/torchtune/models/llama2/test_lora_llama2.py
  tests/torchtune/modules/low_precision/test_nf4_linear.py
  torchtune/models/gemma/_component_builders.py
  torchtune/models/llama2/_component_builders.py
  torchtune/models/llama3/_component_builders.py
  torchtune/models/mistral/_component_builders.py
  torchtune/models/phi3/_component_builders.py
  torchtune/modules/__init__.py
  torchtune/modules/low_precision/__init__.py
  torchtune/modules/low_precision/nf4_linear.py
Labels: enhancement, CLA Signed

#1143 Add Qwen2-7B model to torchtune.
  recipes/configs/qwen2/7B_full.yaml
  recipes/configs/qwen2/7B_full_low_memory.yaml
  recipes/configs/qwen2/7B_lora.yaml
  recipes/configs/qwen2/7B_lora_single_device.yaml
  tests/assets/tiny_bpe_merges.txt
  tests/assets/tiny_bpe_tokenizer.json
  tests/assets/tiny_bpe_vocab.json
  tests/torchtune/models/qwen2/__init__.py
  tests/torchtune/models/qwen2/test_lora_qwen2.py
  tests/torchtune/models/qwen2/test_qwen2.py
  tests/torchtune/models/qwen2/test_qwen2_tokenizer.py
  torchtune/_recipe_registry.py
  torchtune/models/qwen2/__init__.py
  torchtune/models/qwen2/_component_builders.py
  torchtune/models/qwen2/_convert_weights.py
  torchtune/models/qwen2/_model_builders.py
  torchtune/models/qwen2/_positional_embeddings.py
  torchtune/models/qwen2/_tokenizer.py
  torchtune/modules/__init__.py
  torchtune/modules/transformer.py
  torchtune/utils/_checkpointing/_checkpointer.py
  torchtune/utils/_checkpointing/_checkpointer_utils.py
Labels: CLA Signed

#1049 Put model in eval mode for evaluation
  recipes/eleuther_eval.py
Labels: CLA Signed

#1245 Update Qwen2 files to satisfy linter
  torchtune/models/qwen2/_tokenizer.py
  torchtune/utils/_checkpointing/_checkpointer_utils.py
Labels: CLA Signed

#1248 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: CLA Signed
