Repository pytorch/torchtune, pull requests merged in 2024-12, with the labels that each got.

#1953 initial commit
  torchtune/training/precision.py
  torchtune/utils/_device.py
Labels: CLA Signed

#2040 Vector Quantized Embeddings
  tests/torchtune/modules/test_vq_embeddings.py
  torchtune/modules/__init__.py
  torchtune/modules/vq_embeddings.py
Labels: CLA Signed

#2108 Set gloo process group for FSDP with CPU offload
  recipes/full_finetune_distributed.py
  recipes/knowledge_distillation_distributed.py
  recipes/lora_dpo_distributed.py
  recipes/lora_finetune_distributed.py
  recipes/qat_distributed.py
  tests/recipes/test_full_finetune_distributed.py
Labels: CLA Signed

#2124 Llama 3.3 70B
  docs/source/api_ref_models.rst
  recipes/configs/llama3_3/70B_full.yaml
  recipes/configs/llama3_3/70B_lora.yaml
  recipes/configs/llama3_3/70B_qlora.yaml
  torchtune/_recipe_registry.py
  torchtune/models/llama3_3/__init__.py
  torchtune/models/llama3_3/_model_builders.py
Labels: CLA Signed

#2125 Llama 3.3 readme updates
  README.md
Labels: CLA Signed

#2120 Reduce logging output for distributed KD
  recipes/knowledge_distillation_distributed.py
Labels: CLA Signed

#1076 Support Early Exit Loss and/or Layer Dropout
  docs/source/api_ref_modules.rst
  recipes/dev/7B_full_early_exit.yaml
  recipes/dev/early_exit_finetune_distributed.py
  tests/torchtune/modules/test_common_utils.py
  tests/torchtune/modules/test_early_exit_loss.py
  tests/torchtune/modules/test_layer_dropout.py
  torchtune/_recipe_registry.py
  torchtune/modules/__init__.py
  torchtune/modules/common_utils.py
  torchtune/modules/early_exit_loss.py
  torchtune/modules/layer_dropout.py
  torchtune/modules/transformer.py
Labels: CLA Signed

#2074 Update checkpointing directory
  recipes/configs/llama3_2/1B_full_single_device.yaml
  recipes/configs/llama3_2/1B_lora_single_device.yaml
  recipes/lora_finetune_single_device.py
  tests/recipes/test_full_finetune_distributed.py
  tests/recipes/test_full_finetune_single_device.py
  tests/recipes/test_knowledge_distillation_distributed.py
  tests/recipes/test_knowledge_distillation_single_device.py
  tests/recipes/test_lora_dpo_single_device.py
  tests/recipes/test_lora_finetune_distributed.py
  tests/recipes/test_lora_finetune_single_device.py
  tests/recipes/test_ppo_full_finetune_single_device.py
  tests/recipes/utils.py
  tests/regression_tests/test_llama2_7b.py
  tests/torchtune/training/checkpointing/test_checkpointer.py
  torchtune/_cli/download.py
  torchtune/models/convert_weights.py
  torchtune/training/checkpointing/__init__.py
  torchtune/training/checkpointing/_checkpointer.py
  torchtune/training/checkpointing/_utils.py
Labels: CLA Signed

#2127 pass correct arg
  torchtune/training/checkpointing/_checkpointer.py
Labels: CLA Signed

#2128 update configs
  recipes/configs/llama3_2/8B_to_1B_KD_lora_distributed.yaml
  recipes/configs/llama3_2/8B_to_1B_KD_lora_single_device.yaml
  recipes/configs/llama3_3/70B_full.yaml
  recipes/configs/llama3_3/70B_lora.yaml
  recipes/configs/llama3_3/70B_qlora.yaml
  recipes/configs/qwen2/1.5_to_0.5B_KD_lora_distributed.yaml
  recipes/configs/qwen2/1.5_to_0.5B_KD_lora_single_device.yaml
Labels: CLA Signed

#2131 fix qat_lora_test
  tests/recipes/test_qat_lora_finetune_distributed.py
Labels: CLA Signed

#2133 guard ckpt imports
  torchtune/training/checkpointing/_checkpointer.py
Labels: CLA Signed

#2136 [bug fix] add parents=True
  torchtune/training/checkpointing/_checkpointer.py
Labels: CLA Signed

#2135 [bug fix] re-add model
  recipes/configs/llama3_2/1B_full_single_device.yaml
Labels: CLA Signed

#2143 Update save sizes into GiB
  recipes/quantize.py
  torchtune/training/checkpointing/_checkpointer.py
Labels: CLA Signed

#2144 [bug fix] remove config download when source is kaggle
  torchtune/_cli/download.py
  torchtune/training/checkpointing/_checkpointer.py
Labels: CLA Signed

#2146 [fix] remove "with_suffix"
  torchtune/training/checkpointing/_checkpointer.py
  torchtune/training/checkpointing/_utils.py
Labels: CLA Signed

#2139 DoRA fixes
  recipes/knowledge_distillation_distributed.py
  recipes/knowledge_distillation_single_device.py
  recipes/lora_dpo_distributed.py
  recipes/lora_finetune_distributed.py
  recipes/lora_finetune_single_device.py
  recipes/qat_lora_finetune_distributed.py
  tests/recipes/test_lora_finetune_distributed.py
  tests/torchtune/models/llama2/scripts/compare_dora.py
  tests/torchtune/modules/peft/test_dora.py
  torchtune/modules/peft/__init__.py
  torchtune/modules/peft/_utils.py
  torchtune/modules/peft/dora.py
  torchtune/modules/peft/lora.py
Labels: CLA Signed

#2150 [Fix] Llama 3.2 Vision decoder_trainable flag fixed
  tests/torchtune/models/llama3_2_vision/test_llama_vision_lora.py
  torchtune/models/llama3_2_vision/_component_builders.py
  torchtune/models/llama3_2_vision/_model_builders.py
Labels: CLA Signed

#2157 Small readme, config updates
  README.md
  recipes/configs/llama3/8B_dora.yaml
  recipes/configs/llama3/8B_dora_single_device.yaml
  recipes/configs/llama3/8B_qdora_single_device.yaml
  recipes/configs/llama3_1/405B_qlora.yaml
Labels: CLA Signed

#2147 Using `FormattedCheckpointFiles` in configs
  recipes/configs/llama2/70B_lora.yaml
  recipes/configs/llama2/70B_qlora.yaml
  recipes/configs/llama3/70B_full.yaml
  recipes/configs/llama3/70B_lora.yaml
  recipes/configs/llama3_1/70B_full.yaml
  recipes/configs/llama3_1/70B_lora.yaml
  recipes/configs/llama3_3/70B_full.yaml
  recipes/configs/llama3_3/70B_lora.yaml
  recipes/configs/llama3_3/70B_qlora.yaml
  recipes/configs/qwen2_5/14B_lora_single_device.yaml
  recipes/configs/qwen2_5/32B_lora.yaml
  recipes/configs/qwen2_5/72B_lora.yaml
Labels: CLA Signed

#2155 Move ``get_world_size_and_rank`` to utils
  docs/source/api_ref_training.rst
  docs/source/api_ref_utilities.rst
  recipes/dev/early_exit_finetune_distributed.py
  recipes/full_finetune_distributed.py
  recipes/knowledge_distillation_distributed.py
  recipes/lora_dpo_distributed.py
  recipes/lora_finetune_distributed.py
  recipes/qat_distributed.py
  recipes/qat_lora_finetune_distributed.py
  tests/torchtune/training/test_distributed.py
  tests/torchtune/utils/test_device.py
  torchtune/training/_distributed.py
  torchtune/training/_profiler.py
  torchtune/training/metric_logging.py
  torchtune/training/seed.py
  torchtune/utils/__init__.py
  torchtune/utils/_device.py
Labels: CLA Signed

#2006 Faster intermediate checkpoints with DCP async save in TorchTune
  recipes/full_finetune_distributed.py
  recipes/full_finetune_single_device.py
  recipes/knowledge_distillation_distributed.py
  recipes/knowledge_distillation_single_device.py
  recipes/lora_dpo_distributed.py
  recipes/lora_dpo_single_device.py
  recipes/lora_finetune_distributed.py
  recipes/lora_finetune_single_device.py
  recipes/ppo_full_finetune_single_device.py
  recipes/qat_distributed.py
  recipes/qat_lora_finetune_distributed.py
  tests/recipes/test_full_finetune_distributed.py
  tests/test_utils.py
  tests/torchtune/training/checkpointing/test_distributed_checkpointer.py
  torchtune/training/__init__.py
  torchtune/training/checkpointing/__init__.py
  torchtune/training/checkpointing/_checkpoint_client.py
  torchtune/training/checkpointing/_checkpointer.py
  torchtune/training/checkpointing/_utils.py
Labels: CLA Signed, triage review

#1929 torchdata integration - multi-dataset and streaming support
  recipes/configs/llama3_2_vision/11B_lora_multi_dataset.yaml
  recipes/lora_finetune_distributed_multi_dataset.py
  torchtune/_recipe_registry.py
  torchtune/data/_torchdata.py
  torchtune/data/_utils.py
  torchtune/datasets/_sft.py
  torchtune/datasets/multimodal/__init__.py
  torchtune/datasets/multimodal/_the_cauldron.py
  torchtune/utils/_import_guard.py
Labels: CLA Signed

#2165 Allow higher version of lm-eval
  .github/workflows/gpu_test.yaml
  .github/workflows/recipe_test.yaml
  .github/workflows/regression_test.yaml
  recipes/configs/llama3_2_vision/11B_evaluation.yaml
  recipes/eleuther_eval.py
  tests/recipes/test_eleuther_eval.py
Labels: CLA Signed

#2167 Using `FormattedCheckpointFiles` in configs... round 2
  recipes/configs/llama2/70B_lora.yaml
  recipes/configs/llama2/70B_qlora.yaml
  recipes/configs/llama3/70B_full.yaml
  recipes/configs/llama3/70B_lora.yaml
  recipes/configs/llama3_1/405B_qlora.yaml
  recipes/configs/llama3_1/70B_full.yaml
  recipes/configs/llama3_1/70B_lora.yaml
  recipes/configs/llama3_3/70B_full.yaml
  recipes/configs/llama3_3/70B_lora.yaml
  recipes/configs/llama3_3/70B_qlora.yaml
  recipes/configs/qwen2_5/14B_lora_single_device.yaml
  recipes/configs/qwen2_5/32B_lora.yaml
  recipes/configs/qwen2_5/72B_lora.yaml
  tests/torchtune/training/checkpointing/test_checkpointer_utils.py
  torchtune/training/checkpointing/_utils.py
Labels: CLA Signed

#2164 [EZ] Fix set_torch_num_threads in multi-node.
  torchtune/training/_distributed.py
Labels: CLA Signed

#2162 Fix `adapter_config.json` saving in DPO recipes
  recipes/lora_dpo_distributed.py
  recipes/lora_dpo_single_device.py
Labels: CLA Signed

#2174 Fix excessive QAT warning
  torchtune/training/quantization.py
Labels: CLA Signed

#2183 Add output dir to top of all configs
  recipes/configs/eleuther_evaluation.yaml
  recipes/configs/gemma/evaluation.yaml
  recipes/configs/generation.yaml
  recipes/configs/llama2/generation_v2.yaml
  recipes/configs/llama3_2_vision/11B_evaluation.yaml
  recipes/configs/llama3_2_vision/11B_generation_v2.yaml
  recipes/configs/mistral/evaluation.yaml
  recipes/configs/phi3/evaluation.yaml
  recipes/configs/quantization.yaml
  recipes/configs/qwen2/evaluation.yaml
  recipes/dev/7B_full_early_exit.yaml
Labels: CLA Signed

#2182 change saving logic
  torchtune/training/checkpointing/_checkpointer.py
  torchtune/training/checkpointing/_utils.py
Labels: CLA Signed

#2181 output_dir not in ckpt dir
  tests/recipes/test_ppo_full_finetune_single_device.py
  tests/torchtune/training/checkpointing/test_checkpointer.py
  tests/torchtune/training/checkpointing/test_checkpointer_utils.py
  torchtune/training/checkpointing/_checkpointer.py
  torchtune/training/checkpointing/_utils.py
Labels: CLA Signed

#2185 Set teacher ckptr output_dir to match student in KD configs
  recipes/configs/llama3_2/8B_to_1B_KD_lora_distributed.yaml
  recipes/configs/llama3_2/8B_to_1B_KD_lora_single_device.yaml
  recipes/configs/qwen2/1.5_to_0.5B_KD_lora_distributed.yaml
  recipes/configs/qwen2/1.5_to_0.5B_KD_lora_single_device.yaml
Labels: CLA Signed

#2188 raise compile error
  recipes/configs/llama3/8B_qat_lora.yaml
  recipes/configs/llama3_1/8B_qat_lora.yaml
  recipes/configs/llama3_2/1B_qat_lora.yaml
  recipes/configs/llama3_2/3B_qat_lora.yaml
  recipes/qat_distributed.py
  recipes/qat_lora_finetune_distributed.py
Labels: CLA Signed

#2176 Update DPO Max Seq Len
  recipes/configs/llama2/7B_lora_dpo.yaml
  recipes/configs/llama2/7B_lora_dpo_single_device.yaml
  recipes/configs/llama3_1/8B_lora_dpo.yaml
  recipes/configs/llama3_1/8B_lora_dpo_single_device.yaml
Labels: CLA Signed

#2186 Llama3.2 3B eval
  recipes/configs/llama3_2/evaluation.yaml
  torchtune/_recipe_registry.py
Labels: CLA Signed

#2187 Update typo in docstring for _generation.get_causal_mask_from_padding…
  torchtune/generation/_generation.py
Labels: CLA Signed

#2189 new docs for checkpointing
  docs/source/deep_dives/checkpointer.rst
  docs/source/tutorials/e2e_flow.rst
Labels: CLA Signed

#2192 Update E2E Tutorial w/ vLLM and HF Hub
  docs/source/tutorials/e2e_flow.rst
Labels: CLA Signed

#2179 pytorch/torchtune/tests/torchtune/modules/_export
  tests/torchtune/modules/_export/test_attention.py
  tests/torchtune/modules/_export/test_export_position_embeddings.py
Labels: CLA Signed, fb-exported

#2195 update torchtune version
  version.txt
Labels: CLA Signed

#2196 [metric_logging][wandb] Fix wandb metric logger config save path
  torchtune/training/metric_logging.py
Labels: CLA Signed

#2209 Add evaluation file for code_llama2 model
  recipes/configs/code_llama2/evaluation.yaml
  torchtune/_recipe_registry.py
Labels: CLA Signed
