Repository pytorch/torchtune, pull requests merged in 2024-10, with the labels that each got.

#1695 Resizable image positional embeddings
  docs/source/api_ref_models.rst
  tests/torchtune/models/clip/test_pos_embedding_interpolation.py
  torchtune/models/clip/_position_embeddings.py
Labels: CLA Signed

#1728 Unpin numpy
  pyproject.toml
Labels: CLA Signed

#1727 Add HF Checkpoint Format Support for Llama Vision
  torchtune/models/llama3_2_vision/_convert_weights.py
  torchtune/training/checkpointing/_checkpointer.py
Labels: CLA Signed

#1733 config changes
  recipes/configs/llama3/70B_full.yaml
  recipes/configs/llama3/70B_lora.yaml
  recipes/configs/llama3_1/405B_qlora.yaml
  recipes/configs/llama3_1/70B_full.yaml
  recipes/configs/llama3_1/70B_lora.yaml
  recipes/configs/llama3_1/8B_full.yaml
  recipes/configs/llama3_1/8B_full_single_device.yaml
  recipes/configs/llama3_1/8B_lora.yaml
  recipes/configs/llama3_1/8B_lora_single_device.yaml
  recipes/configs/llama3_1/8B_qlora_single_device.yaml
  recipes/configs/llama3_2/1B_full.yaml
  recipes/configs/llama3_2/1B_full_single_device.yaml
  recipes/configs/llama3_2/1B_lora.yaml
  recipes/configs/llama3_2/1B_lora_single_device.yaml
  recipes/configs/llama3_2/1B_qlora_single_device.yaml
  recipes/configs/llama3_2/3B_full.yaml
  recipes/configs/llama3_2/3B_full_single_device.yaml
  recipes/configs/llama3_2/3B_lora.yaml
  recipes/configs/llama3_2/3B_lora_single_device.yaml
  recipes/configs/llama3_2/3B_qlora_single_device.yaml
  recipes/configs/llama3_2/knowledge_distillation_single_device.yaml
  recipes/configs/llama3_2_vision/11B_full.yaml
  recipes/configs/llama3_2_vision/11B_full_single_device.yaml
  recipes/configs/llama3_2_vision/11B_lora.yaml
  recipes/configs/llama3_2_vision/11B_lora_single_device.yaml
  recipes/configs/qwen2/knowledge_distillation_single_device.yaml
Labels: CLA Signed

#1731 Fix custom imports for both distributed and single device
  torchtune/_cli/run.py
  torchtune/config/_instantiate.py
Labels: CLA Signed

#1738 Pin urllib3<2.0.0 to fix eleuther eval errors
  pyproject.toml
Labels: CLA Signed

#1663 Fixing recompiles in KV-cache + compile
  tests/torchtune/modules/test_kv_cache.py
  torchtune/modules/kv_cache.py
Labels: CLA Signed

#1739 Fix CLIP pos embedding interpolation to work on DTensors
  torchtune/models/clip/_position_embeddings.py
Labels: CLA Signed

#1748 Bump version to 0.4.0
  version.txt
Labels: CLA Signed

#1645 [Feat] Activation offloading for distributed lora recipe
  recipes/lora_finetune_distributed.py
Labels: CLA Signed

#1350 Add LR Scheduler to single device full finetune
  recipes/configs/llama2/7B_full_low_memory.yaml
  recipes/configs/llama3/8B_full_single_device.yaml
  recipes/full_finetune_single_device.py
  tests/recipes/test_full_finetune_single_device.py
  torchtune/training/memory.py
Labels: CLA Signed

#1760 Custom recipes use slash path
  torchtune/_cli/run.py
Labels: CLA Signed

#1757 Adds __repr__ to Message
  tests/torchtune/data/test_messages.py
  torchtune/data/_messages.py
Labels: CLA Signed

#1764 Fix save adapter weights only
  recipes/lora_dpo_single_device.py
  recipes/lora_finetune_single_device.py
  tests/recipes/test_lora_dpo_single_device.py
  tests/recipes/test_lora_finetune_distributed.py
  tests/recipes/test_lora_finetune_single_device.py
Labels: CLA Signed

#1761 Set drop_last to always True
  recipes/full_finetune_distributed.py
  recipes/full_finetune_single_device.py
  recipes/knowledge_distillation_single_device.py
  recipes/lora_dpo_distributed.py
  recipes/lora_dpo_single_device.py
  recipes/lora_finetune_distributed.py
  recipes/lora_finetune_single_device.py
  recipes/ppo_full_finetune_single_device.py
  recipes/qat_distributed.py
Labels: CLA Signed

#1772 Remove nonexistent flag for acc offloading in memory_optimizations.rst
  docs/source/tutorials/memory_optimizations.rst
Labels: CLA Signed

#1773 [BUGFIX] Adding sequence truncation to `max_seq_length` in eval recipe
  recipes/eleuther_eval.py
Labels: CLA Signed

#1765 Add ROCm "support"
  .github/workflows/build_linux_wheels.yaml
Labels: CLA Signed, module: rocm, ciflow/rocm

#1778 [BUG] Include system prompt in Phi3 by default
  tests/torchtune/models/phi3/test_phi3_tokenizer.py
  torchtune/models/phi3/_tokenizer.py
Labels: CLA Signed

#1777 Fixing quantization in eval recipe
  recipes/eleuther_eval.py
  tests/recipes/test_eleuther_eval.py
Labels: CLA Signed

#1781 Delete deprecated ChatDataset and InstructDataset
  docs/source/api_ref_datasets.rst
  docs/source/deep_dives/configs.rst
  docs/source/tutorials/datasets.rst
  tests/torchtune/datasets/test_chat_dataset.py
  tests/torchtune/datasets/test_instruct_dataset.py
  torchtune/datasets/__init__.py
  torchtune/datasets/_chat.py
  torchtune/datasets/_instruct.py
Labels: CLA Signed

#1783 Add split argument to required builders and set it default value to "train"
  torchtune/datasets/_chat.py
  torchtune/datasets/_instruct.py
  torchtune/datasets/multimodal/_multimodal.py
Labels: CLA Signed

#1784 Fix quantization with generate
  recipes/generate.py
  torchtune/generation/_generation.py
Labels: CLA Signed

#1787 Fix typo in multimodal_datasets.rst
  docs/source/basics/multimodal_datasets.rst
Labels: CLA Signed

#1785 Make AlpacaToMessage public.
  docs/source/api_ref_data.rst
  torchtune/data/__init__.py
  torchtune/data/_messages.py
  torchtune/datasets/_alpaca.py
Labels: CLA Signed

#1792 Fix misleading attn_dropout docstring
  torchtune/modules/attention.py
Labels: CLA Signed

#1789 Add filter_fn to all generic dataset classes and builders API
  torchtune/datasets/_alpaca.py
  torchtune/datasets/_chat.py
  torchtune/datasets/_cnn_dailymail.py
  torchtune/datasets/_grammar.py
  torchtune/datasets/_hh_rlhf_helpful.py
  torchtune/datasets/_instruct.py
  torchtune/datasets/_preference.py
  torchtune/datasets/_samsum.py
  torchtune/datasets/_slimorca.py
  torchtune/datasets/_stack_exchange_paired.py
  torchtune/datasets/_wikitext.py
  torchtune/datasets/multimodal/_llava_instruct.py
  torchtune/datasets/multimodal/_multimodal.py
  torchtune/datasets/multimodal/_the_cauldron.py
Labels: CLA Signed

#1803 Set dropout in SDPA to 0.0 when not in training mode
  torchtune/modules/attention.py
  torchtune/modules/attention_utils.py
Labels: CLA Signed

#1656 Skip entire header for llama3 decode
  tests/torchtune/models/llama3/test_llama3_tokenizer.py
  tests/torchtune/modules/tokenizers/test_tiktoken.py
  torchtune/models/llama3/_tokenizer.py
  torchtune/models/phi3/_tokenizer.py
  torchtune/modules/tokenizers/_tiktoken.py
Labels: CLA Signed

#1805 Remove unused bsz variable
  torchtune/modules/transformer.py
Labels: CLA Signed, fb-exported

#1802 Adding `max_seq_length` to vision eval config
  recipes/configs/llama3_2_vision/evaluation.yaml
Labels: CLA Signed

#1796 Add check that there is no PackedDataset while building ConcatDataset
  tests/torchtune/datasets/test_concat_dataset.py
  torchtune/datasets/_concat.py
Labels: CLA Signed

#1807 Add posibility to pack in _wikitext.py
  torchtune/datasets/_wikitext.py
Labels: CLA Signed

#1809 Add evaluation configs under qwen2 dir
  recipes/configs/qwen2/evaluation.yaml
  torchtune/_recipe_registry.py
Labels: CLA Signed

#1806 Fix eos_token problem in all required models
  tests/torchtune/models/gemma/test_gemma_tokenizer.py
  tests/torchtune/models/mistral/test_mistral_tokenizer.py
  tests/torchtune/models/phi3/test_phi3_tokenizer.py
  tests/torchtune/models/qwen2/test_qwen2_tokenizer.py
  torchtune/models/gemma/_tokenizer.py
  torchtune/models/mistral/_tokenizer.py
  torchtune/models/phi3/_tokenizer.py
  torchtune/models/qwen2/_tokenizer.py
Labels: CLA Signed

#1812 Torchao version check changes/BC import of TensorCoreTiledLayout
  torchtune/modules/low_precision/_utils.py
  torchtune/training/quantization.py
  torchtune/utils/_import_guard.py
  torchtune/utils/_version.py
Labels: CLA Signed

#1819 1810 move gemma evaluation
  recipes/configs/gemma/evaluation.yaml
  torchtune/_recipe_registry.py
Labels: CLA Signed

#1800 Update EleutherAI Eval Harness to v0.4.5
  .github/workflows/gpu_test.yaml
  .github/workflows/recipe_test.yaml
  .github/workflows/regression_test.yaml
  recipes/configs/llama3_2_vision/evaluation.yaml
  recipes/eleuther_eval.py
  tests/recipes/test_eleuther_eval.py
Labels: CLA Signed

#1822 Add evaluation configs under phi3 dir
  recipes/configs/phi3/evaluation.yaml
  torchtune/_recipe_registry.py
Labels: CLA Signed

#1828 Patch for the patch
  CITATION.cff
  README.md
Labels: CLA Signed

#1756 Create CITATION.cff
  CITATION.cff
  README.md
Labels: CLA Signed

#1832 fixed error message for GatedRepoError
  tests/torchtune/_cli/test_download.py
  torchtune/_cli/download.py
Labels: CLA Signed

#1829 1810 Move mistral evaluation
  recipes/configs/mistral/evaluation.yaml
  torchtune/_recipe_registry.py
Labels: CLA Signed

#1825 More consistent trace names.
  torchtune/training/_profiler.py
Labels: CLA Signed

#1834 fbcode using TensorCoreLayout
  torchtune/utils/_import_guard.py
Labels: CLA Signed, fb-exported

#1836 Remove pad_max_tiles in CLIP
  recipes/configs/llama3_2_vision/11B_full.yaml
  recipes/configs/llama3_2_vision/11B_full_single_device.yaml
  recipes/configs/llama3_2_vision/11B_lora.yaml
  recipes/configs/llama3_2_vision/11B_lora_single_device.yaml
  tests/torchtune/models/clip/test_clip_image_transform.py
  torchtune/data/_collate.py
  torchtune/models/clip/_transform.py
  torchtune/models/llama3_2_vision/_transform.py
Labels: CLA Signed

#1820 Add ``vqa_dataset``, update docs
  tests/assets/rgb_pytorch.png
  tests/assets/vqa_tiny.json
  tests/torchtune/datasets/multimodal/test_vqa_dataset.py
  torchtune/data/_messages.py
  torchtune/datasets/multimodal/__init__.py
  torchtune/datasets/multimodal/_vqa.py
Labels: CLA Signed

#1860 Add offloading tests and fix obscure edge case
  tests/torchtune/training/test_activation_offloading.py
  torchtune/training/_activation_offloading.py
Labels: CLA Signed

#1763 Toggling KV-caches
  docs/source/api_ref_modules.rst
  recipes/eleuther_eval.py
  tests/recipes/test_eleuther_eval.py
  tests/torchtune/modules/model_fusion/test_fusion_layer.py
  tests/torchtune/modules/model_fusion/test_fusion_models.py
  tests/torchtune/modules/test_attention.py
  tests/torchtune/modules/test_common_utils.py
  torchtune/models/clip/_position_embeddings.py
  torchtune/models/gemma/transformer.py
  torchtune/modules/__init__.py
  torchtune/modules/attention.py
  torchtune/modules/common_utils.py
  torchtune/modules/model_fusion/_fusion.py
  torchtune/modules/transformer.py
Labels: CLA Signed

#1876 Cacheing doc nits
  torchtune/modules/common_utils.py
  torchtune/modules/model_fusion/_fusion.py
  torchtune/modules/transformer.py
Labels: CLA Signed

#1881 LoRA typo fix + bias=True
  torchtune/models/clip/_component_builders.py
  torchtune/models/llama3_2_vision/_model_builders.py
Labels: CLA Signed

#1886 Correct `torchao` check for `TensorCoreTiledLayout`
  torchtune/utils/_import_guard.py
Labels: CLA Signed

#1885 Kd_loss avg over tokens
  tests/recipes/test_knowledge_distillation_single_device.py
  torchtune/modules/loss/kd_losses.py
Labels: CLA Signed

#1833 Support Optimizer-in-the-backward
  docs/source/api_ref_training.rst
  recipes/full_finetune_distributed.py
  recipes/full_finetune_single_device.py
  tests/recipes/test_full_finetune_distributed.py
  torchtune/training/__init__.py
  torchtune/training/lr_schedulers.py
Labels: CLA Signed

#1892 Remove deprecated `GemmaTransformerDecoder`
  torchtune/models/gemma/transformer.py
Labels: CLA Signed

#1891 Add PromptTemplate examples
  docs/source/basics/prompt_templates.rst
Labels: CLA Signed

#1896 Temporarily disable building Python 3.13 version of torchtune
  .github/workflows/build_linux_wheels.yaml
Labels: CLA Signed

#1889 [bug] fix sharding multimodal
  recipes/configs/llama3_2_vision/11B_full.yaml
  recipes/full_finetune_distributed.py
  recipes/lora_dpo_distributed.py
  recipes/lora_finetune_distributed.py
  recipes/qat_distributed.py
  torchtune/training/__init__.py
  torchtune/training/_distributed.py
Labels: CLA Signed

#1899 Block on Python 3.13 version
  .github/workflows/build_linux_wheels.yaml
Labels: CLA Signed

#1875 Normalize CE loss by total number of (non-padding) tokens
  recipes/full_finetune_distributed.py
  recipes/full_finetune_single_device.py
  recipes/knowledge_distillation_single_device.py
  recipes/lora_finetune_distributed.py
  recipes/lora_finetune_single_device.py
  recipes/qat_distributed.py
  tests/recipes/test_full_finetune_distributed.py
  tests/recipes/test_full_finetune_single_device.py
  tests/recipes/test_knowledge_distillation_single_device.py
  tests/recipes/test_lora_finetune_distributed.py
  tests/recipes/test_lora_finetune_single_device.py
  tests/recipes/test_qat_distributed.py
  torchtune/modules/loss/ce_chunked_output_loss.py
Labels: CLA Signed

#1882 nit: remove (nightly) in recipes
  recipes/configs/llama3/70B_full.yaml
  recipes/configs/llama3_1/405B_qlora.yaml
  recipes/configs/llama3_1/70B_full.yaml
Labels: CLA Signed

#1912 Make TensorCoreTiledLayout import more robust
  torchtune/training/quantization.py
  torchtune/utils/_import_guard.py
Labels: CLA Signed

#1915 [ez] Fix README download example
  README.md
Labels: CLA Signed

#1910 [docs] Custom components page
  docs/source/basics/custom_components.rst
  docs/source/index.rst
Labels: CLA Signed

#1883 Update imports after QAT was moved out of prototype
  torchtune/training/quantization.py
Labels: CLA Signed

#1916 Updating memory optimization overview
  docs/source/index.rst
  docs/source/tutorials/memory_optimizations.rst
Labels: CLA Signed

#1914 Patch github link in torchtune docs header
  docs/source/_templates/layout.html
Labels: CLA Signed

#1918 Fixing DoRA docs, adding to mem opt tutorial
  docs/source/api_ref_modules.rst
  docs/source/recipes/lora_finetune_single_device.rst
  docs/source/tutorials/memory_optimizations.rst
  torchtune/modules/peft/dora.py
Labels: CLA Signed

#1631 Add KD distributed recipe
  recipes/configs/llama3_2/knowledge_distillation_distributed.yaml
  recipes/configs/qwen2/knowledge_distillation_distributed.yaml
  recipes/knowledge_distillation_distributed.py
  tests/recipes/test_knowledge_distillation_distributed.py
  torchtune/_recipe_registry.py
Labels: CLA Signed

#1924 add missing doc
  torchtune/datasets/_text_completion.py
Labels: CLA Signed

#1920 [FIX] MM Eval Mask Sizes
  recipes/dev/generate_v2.py
  recipes/eleuther_eval.py
  tests/torchtune/data/test_collate.py
  tests/torchtune/modules/transforms/test_transforms.py
  torchtune/data/_collate.py
  torchtune/models/llama3_2_vision/_transform.py
  torchtune/modules/transforms/_transforms.py
Labels: CLA Signed

#1863 Qwen2.5
  recipes/configs/qwen2_5/0_5B_full.yaml
  recipes/configs/qwen2_5/0_5B_full_single_device.yaml
  recipes/configs/qwen2_5/0_5B_lora.yaml
  recipes/configs/qwen2_5/0_5B_lora_single_device.yaml
  recipes/configs/qwen2_5/14B_lora_single_device.yaml
  recipes/configs/qwen2_5/1_5B_full.yaml
  recipes/configs/qwen2_5/1_5B_full_single_device.yaml
  recipes/configs/qwen2_5/1_5B_lora.yaml
  recipes/configs/qwen2_5/1_5B_lora_single_device.yaml
  recipes/configs/qwen2_5/32B_lora.yaml
  recipes/configs/qwen2_5/3B_full.yaml
  recipes/configs/qwen2_5/3B_full_single_device.yaml
  recipes/configs/qwen2_5/3B_lora.yaml
  recipes/configs/qwen2_5/3B_lora_single_device.yaml
  recipes/configs/qwen2_5/72B_lora.yaml
  recipes/configs/qwen2_5/7B_full.yaml
  recipes/configs/qwen2_5/7B_full_single_device.yaml
  recipes/configs/qwen2_5/7B_lora.yaml
  recipes/configs/qwen2_5/7B_lora_single_device.yaml
  tests/torchtune/models/qwen2/test_qwen2_tokenizer.py
  tests/torchtune/models/qwen2_5/__init__.py
  tests/torchtune/models/qwen2_5/test_tokenizer.py
  torchtune/_recipe_registry.py
  torchtune/models/qwen2/__init__.py
  torchtune/models/qwen2/_model_builders.py
  torchtune/models/qwen2/_tokenizer.py
  torchtune/models/qwen2_5/__init__.py
  torchtune/models/qwen2_5/_model_builders.py
  torchtune/models/qwen2_5/_tokenizer.py
Labels: CLA Signed

#1917 Restore backward after each batch for grad accum
  recipes/full_finetune_distributed.py
  recipes/full_finetune_single_device.py
  recipes/knowledge_distillation_distributed.py
  recipes/knowledge_distillation_single_device.py
  recipes/lora_finetune_distributed.py
  recipes/lora_finetune_single_device.py
  recipes/qat_distributed.py
  tests/recipes/test_full_finetune_distributed.py
  tests/recipes/test_full_finetune_single_device.py
  tests/recipes/test_lora_finetune_distributed.py
  tests/recipes/test_qat_distributed.py
  torchtune/training/__init__.py
  torchtune/training/_grad_scaler.py
Labels: CLA Signed

#1909 Fix lora single device fine tune checkpoint saving & nan loss when use_dora=True
  recipes/lora_finetune_single_device.py
  tests/recipes/test_lora_finetune_single_device.py
  tests/recipes/utils.py
  torchtune/models/convert_weights.py
  torchtune/modules/peft/dora.py
Labels: CLA Signed
