Repository pytorch/torchtune, pull requests merged in 2025-01, with the labels that each got.

#2219 Adds message_transform link from SFTDataset docstring to docs
  torchtune/datasets/_sft.py
Labels: CLA Signed

#2228 Set default value for 'subset' parameter in the_cauldron_dataset
  torchtune/datasets/multimodal/_the_cauldron.py
Labels: CLA Signed

#2230 Add eval config for QWEN2_5 model using 0.5B variant
  recipes/configs/qwen2_5/evaluation.yaml
  torchtune/_recipe_registry.py
Labels: CLA Signed

#2069 T5 Encoder
  tests/assets/sentencepiece.model
  tests/torchtune/models/t5/__init__.py
  tests/torchtune/models/t5/test_t5_encoder.py
  tests/torchtune/models/t5/test_t5_tokenizer.py
  torchtune/models/t5/__init__.py
  torchtune/models/t5/_component_builders.py
  torchtune/models/t5/_convert_weights.py
  torchtune/models/t5/_encoder.py
  torchtune/models/t5/_model_builders.py
  torchtune/models/t5/_tokenizer.py
  torchtune/modules/tokenizers/_sentencepiece.py
  torchtune/training/checkpointing/_checkpointer.py
  torchtune/training/checkpointing/_utils.py
Labels: CLA Signed

#2138 Migrate distributed state dict API
  recipes/dev/early_exit_finetune_distributed.py
  recipes/full_finetune_distributed.py
  recipes/knowledge_distillation_distributed.py
  recipes/lora_dpo_distributed.py
  recipes/lora_finetune_distributed.py
  recipes/lora_finetune_distributed_multi_dataset.py
  recipes/qat_distributed.py
  recipes/qat_lora_finetune_distributed.py
  tests/torchtune/modules/peft/test_dora.py
  tests/torchtune/training/test_distributed.py
  torchtune/training/_distributed.py
  torchtune/training/checkpointing/_checkpoint_client.py
Labels: CLA Signed, distributed

#2098 Flux Autoencoder
  tests/torchtune/models/flux/__init__.py
  tests/torchtune/models/flux/test_flux_autoencoder.py
  torchtune/models/flux/__init__.py
  torchtune/models/flux/_autoencoder.py
  torchtune/models/flux/_convert_weights.py
  torchtune/models/flux/_model_builders.py
Labels: CLA Signed

#2172 Fix gradient scaling to account for world_size normalization
  recipes/full_finetune_distributed.py
  recipes/knowledge_distillation_distributed.py
  recipes/lora_finetune_distributed.py
  recipes/lora_finetune_distributed_multi_dataset.py
  recipes/qat_distributed.py
  recipes/qat_lora_finetune_distributed.py
Labels: CLA Signed

#2242 [Small fix] Update CUDA version in README
  .github/workflows/gpu_test.yaml
  README.md
  docs/source/install.rst
Labels: CLA Signed

#2203 llama 3.1 has correct `max_seq_len` for all versions
  torchtune/models/llama3_1/_model_builders.py
Labels: CLA Signed

#2248 Log grad norm aggregated over all ranks, not just rank zero
  recipes/dev/early_exit_finetune_distributed.py
  recipes/full_finetune_distributed.py
  recipes/lora_finetune_distributed.py
  recipes/lora_finetune_distributed_multi_dataset.py
  recipes/qat_distributed.py
  recipes/qat_lora_finetune_distributed.py
Labels: CLA Signed

#2244 Remove example inputs from aoti_compile_and_package
  tests/torchtune/modules/_export/test_export_position_embeddings.py
Labels: CLA Signed, fb-exported

#2252 Fix issue #2243, update the document to show correct usage
  docs/source/tutorials/llama3.rst
Labels: CLA Signed

#2256 Small formatting fix
  tests/torchtune/models/qwen2_5/test_tokenizer.py
Labels: CLA Signed

#2247 Multi-tile support in vision rope
  tests/torchtune/modules/test_position_embeddings.py
  torchtune/models/clip/_component_builders.py
  torchtune/modules/position_embeddings.py
Labels: CLA Signed

#2265 Add AlpacaToMessages to message transforms doc page
  docs/source/basics/message_transforms.rst
Labels: CLA Signed

#2239 Add a "division by zero" check in chunked loss handling in kd_losses.py
  tests/torchtune/modules/loss/test_kd_losses.py
  torchtune/modules/loss/kd_losses.py
Labels: CLA Signed

#2163 Fixing docstring linter
  .pre-commit-config.yaml
  pyproject.toml
  torchtune/data/_collate.py
  torchtune/data/_messages.py
  torchtune/data/_utils.py
  torchtune/models/clip/_position_embeddings.py
  torchtune/models/gemma2/_attention.py
  torchtune/models/phi3/_tokenizer.py
  torchtune/modules/attention.py
  torchtune/modules/kv_cache.py
  torchtune/modules/peft/_utils.py
  torchtune/modules/transformer.py
  torchtune/modules/vision_transformer.py
  torchtune/training/_activation_offloading.py
  torchtune/training/checkpointing/_checkpointer.py
  torchtune/training/checkpointing/_utils.py
  torchtune/utils/_device.py
Labels: CLA Signed

#2066 PPO Performance Improvements
  recipes/configs/mistral/7B_full_ppo_low_memory.yaml
  recipes/ppo_full_finetune_single_device.py
  tests/torchtune/generation/test_generation.py
  tests/torchtune/rlhf/test_rewards.py
  tests/torchtune/training/test_pooling.py
  torchtune/generation/_generation.py
  torchtune/modules/kv_cache.py
  torchtune/modules/transformer.py
  torchtune/rlhf/loss/ppo.py
  torchtune/rlhf/rewards.py
  torchtune/training/pooling.py
Labels: CLA Signed, rlhf

#2234 Add Ascend NPU as a backend for single device recipes
  recipes/dev/generate_v2.py
  recipes/eleuther_eval.py
  recipes/full_finetune_single_device.py
  recipes/generate.py
  recipes/knowledge_distillation_single_device.py
  recipes/lora_dpo_single_device.py
  recipes/lora_finetune_single_device.py
  recipes/quantize.py
  tests/torchtune/training/test_precision.py
  torchtune/training/precision.py
Labels: CLA Signed

#2271 Fix a bug in set float32 precision
  tests/torchtune/training/test_precision.py
  torchtune/training/precision.py
Labels: CLA Signed

#2276 Construct EarlyFusion's encoder_token_ids on correct device
  torchtune/modules/model_fusion/_early_fusion.py
Labels: CLA Signed

#2278 Sample packing for ConcatDataset
  recipes/dev/early_exit_finetune_distributed.py
  recipes/full_finetune_distributed.py
  recipes/full_finetune_single_device.py
  recipes/knowledge_distillation_distributed.py
  recipes/knowledge_distillation_single_device.py
  recipes/lora_finetune_distributed.py
  recipes/lora_finetune_single_device.py
  recipes/qat_distributed.py
  recipes/qat_lora_finetune_distributed.py
  tests/torchtune/datasets/test_concat_dataset.py
  torchtune/datasets/_concat.py
Labels: CLA Signed

#2274 Logging resolved config
  torchtune/training/metric_logging.py
Labels: CLA Signed

#2290 Removing `SimPOLoss`
  docs/source/api_ref_rlhf.rst
  docs/source/recipes/dpo.rst
  tests/torchtune/rlhf/loss/test_dpo_loss.py
  torchtune/rlhf/loss/__init__.py
  torchtune/rlhf/loss/dpo.py
Labels: CLA Signed

#2291 Proper prefix handling in EarlyFusion sd hooks
  tests/torchtune/modules/model_fusion/test_early_fusion.py
  torchtune/modules/model_fusion/_early_fusion.py
Labels: CLA Signed

#2293 Remove deprecated components for 0.6.0
  torchtune/modules/peft/_utils.py
  torchtune/training/quantization.py
Labels: CLA Signed

#2251 Update the e2e flow tutorial to fix errors of generate
  docs/source/tutorials/e2e_flow.rst
Labels: CLA Signed

#2249 profiling ops on xpu
  recipes/dev/early_exit_finetune_distributed.py
  recipes/full_finetune_distributed.py
  recipes/full_finetune_single_device.py
  recipes/knowledge_distillation_distributed.py
  recipes/knowledge_distillation_single_device.py
  recipes/lora_finetune_distributed.py
  recipes/lora_finetune_distributed_multi_dataset.py
  recipes/lora_finetune_single_device.py
  recipes/ppo_full_finetune_single_device.py
  recipes/qat_distributed.py
  recipes/qat_lora_finetune_distributed.py
  tests/torchtune/training/test_profiler.py
  torchtune/training/_profiler.py
Labels: CLA Signed

#2231 Refactored modules/tokenizers to be a subdir of modules/transforms
  docs/source/api_ref_modules.rst
  docs/source/basics/custom_components.rst
  docs/source/basics/model_transforms.rst
  docs/source/basics/tokenizers.rst
  recipes/eleuther_eval.py
  tests/test_utils.py
  tests/torchtune/modules/transforms/tokenizers/test_sentencepiece.py
  tests/torchtune/modules/transforms/tokenizers/test_tiktoken.py
  tests/torchtune/modules/transforms/tokenizers/test_utils.py
  torchtune/data/_messages.py
  torchtune/datasets/_alpaca.py
  torchtune/datasets/_chat.py
  torchtune/datasets/_cnn_dailymail.py
  torchtune/datasets/_grammar.py
  torchtune/datasets/_hh_rlhf_helpful.py
  torchtune/datasets/_instruct.py
  torchtune/datasets/_preference.py
  torchtune/datasets/_samsum.py
  torchtune/datasets/_sft.py
  torchtune/datasets/_slimorca.py
  torchtune/datasets/_stack_exchange_paired.py
  torchtune/datasets/_text_completion.py
  torchtune/datasets/_wikitext.py
  torchtune/models/clip/_tokenizer.py
  torchtune/models/gemma/_tokenizer.py
  torchtune/models/llama2/_tokenizer.py
  torchtune/models/llama3/_model_builders.py
  torchtune/models/llama3/_tokenizer.py
  torchtune/models/llama3_2_vision/_transform.py
  torchtune/models/mistral/_tokenizer.py
  torchtune/models/phi3/_model_builders.py
  torchtune/models/phi3/_tokenizer.py
  torchtune/models/qwen2/_model_builders.py
  torchtune/models/qwen2/_tokenizer.py
  torchtune/models/qwen2_5/_model_builders.py
  torchtune/models/t5/_tokenizer.py
  torchtune/modules/tokenizers/__init__.py
  torchtune/modules/transforms/tokenizers/__init__.py
  torchtune/modules/transforms/tokenizers/_sentencepiece.py
  torchtune/modules/transforms/tokenizers/_tiktoken.py
  torchtune/modules/transforms/tokenizers/_utils.py
Labels: CLA Signed

#2282 Update model builders
  tests/recipes/dev/test_generate_v2.py
  tests/torchtune/models/t5/test_t5_encoder.py
  torchtune/models/gemma/_component_builders.py
  torchtune/models/gemma2/_component_builders.py
  torchtune/models/llama2/_component_builders.py
  torchtune/models/llama3/_component_builders.py
  torchtune/models/llama3_1/_component_builders.py
  torchtune/models/llama3_2/_component_builders.py
  torchtune/models/llama3_2_vision/_component_builders.py
  torchtune/models/mistral/_component_builders.py
  torchtune/models/phi3/_component_builders.py
  torchtune/models/qwen2/_component_builders.py
  torchtune/models/t5/_component_builders.py
  torchtune/models/t5/_encoder.py
Labels: CLA Signed

#2308 [EZ] Only log deprecation warning on rank zero
  torchtune/utils/_logging.py
Labels: CLA Signed

#2309 [ez] Add output_dir field to a couple configs
  recipes/configs/code_llama2/evaluation.yaml
  recipes/configs/llama3_2/evaluation.yaml
  recipes/configs/llama3_2_vision/11B_lora_multi_dataset.yaml
Labels: CLA Signed

#2314 Disable DSD and fix bitsandbytes test
  tests/torchtune/modules/low_precision/test_nf4_linear.py
  torchtune/training/_distributed.py
Labels: CLA Signed

#2317 fix state dict hook for early fusion models
  torchtune/modules/model_fusion/_early_fusion.py
Labels: CLA Signed

#2094 Adding reverse and symmetric KLD losses
  tests/torchtune/modules/loss/test_kd_losses.py
  torchtune/modules/loss/__init__.py
  torchtune/modules/loss/kd_losses.py
  torchtune/training/_compile.py
Labels: CLA Signed

#2298 [WIP] 'tune cat' command for pretty printing configuration files
  docs/source/tune_cli.rst
  tests/torchtune/_cli/test_cat.py
  torchtune/_cli/cat.py
  torchtune/_cli/tune.py
Labels: CLA Signed

#2322 Use checkout@v4 / upload@v4 for docs build
  .github/workflows/build_docs.yaml
Labels: CLA Signed

#2304 Fix stop tokens in PPO
  recipes/ppo_full_finetune_single_device.py
Labels: CLA Signed
