Repository pytorch/torchtune, pull requests merged in 2025-04, with the labels that each got.

#2522 Fix GRPO profiling
  recipes/dev/grpo_full_finetune_distributed.py
Labels: wontfix, CLA Signed

#2510 REMOVE `recursive_reshard` UTILITY
  recipes/dev/grpo_full_finetune_distributed.py
  torchtune/training/_distributed.py
Labels: CLA Signed

#2544 improve ckpt error handling and docs
  docs/source/deep_dives/checkpointer.rst
  torchtune/training/checkpointing/_utils.py
Labels: CLA Signed

#2549 Replace exponential with torch.log in generation sampling
  .github/workflows/gpu_test.yaml
  tests/recipes/dev/test_generate_v2.py
  tests/recipes/test_eleuther_eval.py
  tests/torchtune/generation/test_generation.py
  tests/torchtune/modules/peft/test_dora.py
  tests/torchtune/training/test_distributed.py
  torchtune/generation/_generation.py
Labels: CLA Signed

#2557 Use DCP in HFCheckpointer to read/write directly to HuggingFace
  tests/torchtune/training/checkpointing/test_checkpointer.py
  torchtune/training/checkpointing/_checkpointer.py
  torchtune/training/checkpointing/_utils.py
Labels: CLA Signed

#2321 Refactor validate missing for LoRA + deprecate param utility
  recipes/dev/lora_finetune_distributed_multi_dataset.py
  recipes/knowledge_distillation_distributed.py
  recipes/knowledge_distillation_single_device.py
  recipes/lora_dpo_distributed.py
  recipes/lora_dpo_single_device.py
  recipes/lora_finetune_distributed.py
  recipes/lora_finetune_single_device.py
  recipes/qat_lora_finetune_distributed.py
  tests/torchtune/modules/peft/test_utils.py
  tests/torchtune/training/checkpointing/test_checkpointer.py
  tests/torchtune/utils/test_logging.py
  torchtune/modules/peft/_utils.py
  torchtune/utils/_logging.py
Labels: CLA Signed

#2567 [release-only] Bump version for 0.6.1 release
  version.txt
Labels: CLA Signed

#2423 [RFC] Proposal to Update PPO Test to Add LR Scheduler
  recipes/configs/mistral/7B_full_ppo_low_memory.yaml
  recipes/ppo_full_finetune_single_device.py
  tests/recipes/test_ppo_full_finetune_single_device.py
Labels: CLA Signed

#2566 Allow tensor resize HFLoadPlanner
  torchtune/training/checkpointing/_checkpointer.py
Labels: CLA Signed

#2571 Revert back to ``safe_open`` and don't use buffer
  torchtune/training/checkpointing/_utils.py
Labels: CLA Signed, ci-no-td

#2560 fix: Timeout crash because of chunked_output len
  tests/torchtune/modules/loss/test_ce_chunked_output_loss.py
  tests/torchtune/modules/loss/test_kd_losses.py
  tests/torchtune/modules/test_transformer_decoder.py
  torchtune/modules/loss/ce_chunked_output_loss.py
  torchtune/modules/loss/kd_losses.py
  torchtune/modules/transformer.py
Labels: CLA Signed

#2581 typo fix
  recipes/configs/llama4/scout_17B_16E_full.yaml
Labels: CLA Signed

#2582 Bold Llama4 in readme, expose scaled RoPE in Scout builder
  README.md
  torchtune/models/llama4/_model_builders.py
Labels: CLA Signed

#2584 Replace logged loss .item() with .detach().item()
  recipes/dev/early_exit_finetune_distributed.py
  recipes/dev/lora_finetune_distributed_multi_dataset.py
  recipes/full_dpo_distributed.py
  recipes/full_finetune_distributed.py
  recipes/full_finetune_single_device.py
  recipes/knowledge_distillation_distributed.py
  recipes/knowledge_distillation_single_device.py
  recipes/lora_dpo_distributed.py
  recipes/lora_dpo_single_device.py
  recipes/lora_finetune_distributed.py
  recipes/lora_finetune_single_device.py
  recipes/qat_distributed.py
  recipes/qat_lora_finetune_distributed.py
Labels: CLA Signed

#2591 Fix TP test expected values
  tests/recipes/test_full_finetune_distributed.py
Labels: CLA Signed

#2425 Padding bug in GRPO
  recipes/dev/grpo_full_finetune_distributed.py
  torchtune/dev/grpo/rewards.py
Labels: CLA Signed

#2595 Unbreak our CI
  .github/workflows/gpu_test.yaml
  .github/workflows/recipe_test.yaml
  tests/recipes/test_eleuther_eval.py
  tests/recipes/test_full_finetune_distributed.py
  tests/recipes/test_full_finetune_single_device.py
  tests/recipes/test_knowledge_distillation_distributed.py
  tests/recipes/test_knowledge_distillation_single_device.py
  tests/recipes/test_lora_dpo_distributed.py
  tests/recipes/test_lora_dpo_single_device.py
  tests/recipes/test_lora_finetune_single_device.py
  tests/recipes/test_ppo_full_finetune_single_device.py
  tests/recipes/test_qat_distributed.py
  tests/recipes/test_qat_lora_finetune_distributed.py
  tests/test_utils.py
  torchtune/models/llama3/_tokenizer.py
Labels: CLA Signed

#2593 Fix 2d Rope
  recipes/configs/llama4/scout_17B_16E_generation_distributed.yaml
  recipes/dev/generate_v2.py
  recipes/dev/generate_v2_distributed.py
  torchtune/data/_collate.py
  torchtune/models/llama4/_convert_weights.py
  torchtune/models/llama4/_encoder.py
  torchtune/models/llama4/_model_builders.py
  torchtune/modules/position_embeddings.py
Labels: CLA Signed

#2576 Adapter size calls should use fsspec
  torchtune/training/checkpointing/_checkpointer.py
  torchtune/training/checkpointing/_utils.py
Labels: CLA Signed

#2607 Change README badge to follow gpu_test instead of recipe_test
  README.md
Labels: CLA Signed

#2603 Fix Llama tokenizer failing to decode some tokens, but this time correctly
  tests/torchtune/models/llama3/test_llama3_tokenizer.py
  tests/torchtune/models/qwen2_5/test_tokenizer.py
  torchtune/models/qwen2/_tokenizer.py
Labels: CLA Signed

#2546 Enable FP8 full finetune distributed
  recipes/full_finetune_distributed.py
  tests/torchtune/training/test_quantization.py
  torchtune/models/llama3/_parallelism.py
  torchtune/training/quantization.py
Labels: CLA Signed

#2612 fix `--hf_token` to `--hf-token` in llama kd tutorial
  docs/source/tutorials/llama_kd_tutorial.rst
Labels: CLA Signed

#2611 Fix flaky test related to jmespath
  .github/workflows/gpu_test.yaml
Labels: CLA Signed

#2613 [Fix] Incorrect Labels Shift for Packed Data
  recipes/dev/early_exit_finetune_distributed.py
  recipes/dev/lora_finetune_distributed_multi_dataset.py
  recipes/full_finetune_distributed.py
  recipes/full_finetune_single_device.py
  recipes/knowledge_distillation_distributed.py
  recipes/knowledge_distillation_single_device.py
  recipes/lora_finetune_distributed.py
  recipes/lora_finetune_single_device.py
  recipes/qat_distributed.py
  recipes/qat_lora_finetune_distributed.py
  tests/torchtune/datasets/multimodal/test_vqa_dataset.py
  tests/torchtune/datasets/test_alpaca_dataset.py
  tests/torchtune/datasets/test_chat_dataset.py
  tests/torchtune/datasets/test_concat_dataset.py
  tests/torchtune/datasets/test_grammar_dataset.py
  tests/torchtune/datasets/test_instruct_dataset.py
  tests/torchtune/datasets/test_packed_dataset.py
  tests/torchtune/datasets/test_samsum_dataset.py
  tests/torchtune/datasets/test_sft_dataset.py
  tests/torchtune/datasets/test_text_completion_dataset.py
  torchtune/datasets/_sft.py
  torchtune/datasets/_text_completion.py
Labels: CLA Signed

#2615 Chore/llama-use-hf-ckpt
  recipes/configs/llama2/13B_full.yaml
  recipes/configs/llama2/13B_lora.yaml
  recipes/configs/llama2/13B_qlora_single_device.yaml
  recipes/configs/llama2/70B_lora.yaml
  recipes/configs/llama2/70B_qlora.yaml
  recipes/configs/llama2/7B_full.yaml
  recipes/configs/llama2/7B_full_low_memory.yaml
  recipes/configs/llama2/7B_lora.yaml
  recipes/configs/llama2/7B_lora_dpo.yaml
  recipes/configs/llama2/7B_lora_dpo_single_device.yaml
  recipes/configs/llama2/7B_lora_single_device.yaml
  recipes/configs/llama2/7B_qat_full.yaml
  recipes/configs/llama2/7B_qlora.yaml
  recipes/configs/llama2/7B_qlora_single_device.yaml
  recipes/configs/llama2/generation_v2.yaml
  recipes/configs/llama3/8B_dora.yaml
  recipes/configs/llama3/8B_dora_single_device.yaml
  recipes/configs/llama3/8B_full.yaml
  recipes/configs/llama3/8B_full_single_device.yaml
  recipes/configs/llama3/8B_lora.yaml
  recipes/configs/llama3/8B_lora_single_device.yaml
  recipes/configs/llama3/8B_qat_full.yaml
  recipes/configs/llama3/8B_qat_lora.yaml
  recipes/configs/llama3/8B_qdora_single_device.yaml
  recipes/configs/llama3/8B_qlora_single_device.yaml
Labels: CLA Signed

#2616 Fix docstring for `ConcatDataset`
  torchtune/datasets/_concat.py
Labels: CLA Signed

#2619 Add `padded_collate_packed` to api ref
  docs/source/api_ref_data.rst
Labels: CLA Signed

#2580 Xpudoc
  README.md
  docs/source/install.rst
Labels: CLA Signed

#2605 Add XCCL backend for distributed recipes
  recipes/dev/lora_finetune_distributed_multi_dataset.py
  recipes/full_dpo_distributed.py
  recipes/full_finetune_distributed.py
  recipes/knowledge_distillation_distributed.py
  recipes/lora_dpo_distributed.py
  recipes/lora_finetune_distributed.py
  torchtune/training/_distributed.py
Labels: CLA Signed

#2620 LoRA tested on multi-node
  README.md
Labels: CLA Signed

#2589 Add kd recipe for Qwen2 models
  recipes/configs/qwen2_5/14B_to_7B_KD_lora_single_device.yaml
Labels: CLA Signed

#2626 Update README.md to clarify minimum tested PyTorch version
  README.md
Labels: CLA Signed

#2633 bump version check in 2d parallel loss test
  tests/recipes/test_full_finetune_distributed.py
Labels: CLA Signed

#2583 LoRA + Llama4
  README.md
  recipes/configs/llama4/scout_17B_16E_lora.yaml
  recipes/dev/lora_finetune_distributed_multi_dataset.py
  recipes/knowledge_distillation_distributed.py
  recipes/lora_dpo_distributed.py
  recipes/lora_finetune_distributed.py
  recipes/qat_lora_finetune_distributed.py
  tests/torchtune/models/llama3_2_vision/test_llama_vision_lora.py
  tests/torchtune/modules/moe/test_experts.py
  torchtune/_recipe_registry.py
  torchtune/models/llama3_2_vision/_component_builders.py
  torchtune/models/llama3_2_vision/_model_builders.py
  torchtune/models/llama4/__init__.py
  torchtune/models/llama4/_component_builders.py
  torchtune/models/llama4/_model_builders.py
  torchtune/modules/moe/__init__.py
  torchtune/modules/moe/experts.py
  torchtune/modules/peft/__init__.py
  torchtune/modules/peft/_utils.py
  torchtune/modules/peft/lora.py
Labels: CLA Signed

#2650 Revert change from MultiProcessTestCase to FSDPTest
  tests/torchtune/modules/peft/test_dora.py
  tests/torchtune/training/test_distributed.py
Labels: CLA Signed, ci-no-td

#2653 [ez] fix checkpoint paths for llama3 configs
  recipes/configs/llama3/8B_dora.yaml
  recipes/configs/llama3/8B_dora_single_device.yaml
  recipes/configs/llama3/8B_full.yaml
  recipes/configs/llama3/8B_full_single_device.yaml
  recipes/configs/llama3/8B_lora.yaml
  recipes/configs/llama3/8B_lora_single_device.yaml
  recipes/configs/llama3/8B_qat_full.yaml
  recipes/configs/llama3/8B_qat_lora.yaml
  recipes/configs/llama3/8B_qdora_single_device.yaml
  recipes/configs/llama3/8B_qlora_single_device.yaml
Labels: CLA Signed
